# -*- coding: utf-8 -*-
"""Netflix_movie_rec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASWWHuR74GtM6Gufw1jCGBpzA1O_Nzfw
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("netflix.csv")
print(df.head())

print("first 5 rows")
print(df.head())

print("\ndataset shape")
print(df.shape)

print("\ninfo")
print(df.info())

print("\nmissing value")
print(df.isnull().sum())

print("\nstatistical summary")
print(df.describe())

plt.figure(figsize=(8,5))
df['rating'].value_counts().plot(kind='bar')
plt.title("Netflix Content by Rating")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(10,5))
df['release_year'].value_counts().sort_index().plot(kind='line')
plt.title("Content Released by Year")
plt.xlabel("Year")
plt.ylabel("Number of Titles")
plt.show()

plt.figure(figsize=(8,5))
df['user_rating_score'].dropna().hist(bins=20)
plt.title("User Rating Score Distribution")
plt.xlabel("User Rating Score")
plt.ylabel("Frequency")
plt.show()

print("\n===== top 10 titles =====")

top_titles = df.sort_values(
    by='user_rating_score',
    ascending=False
)

print(top_titles[['title', 'user_rating_score']].head(10))

print("\nOldest Release Year:")
print(df['release_year'].min())

print("\nLatest Release Year:")
print(df['release_year'].max())

print("\nAverage User Rating:")
print(df['user_rating_score'].mean())